version: '3.7'
services:
  db:
    image: postgres:15
    container_name: bookit_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: bookit_redis
    ports:
      - "6379:6379"

  bookit:
    image: bookit_image
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/booking/docker/app.sh"]
    ports:
      - "7777:8000"

  celery:
    image: bookit_celery
    build:
      context: .
    container_name: bookit_celery
    command: ["/booking/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis


  flower:
    image: bookit_flower
    build:
      context: .
    container_name: bookit_flower
    command: ["/booking/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

